GET http://localhost:3000/filmes

###
POST http://localhost:3000/adicionar-filme
Content-Type: application/json

{
    "titulo":"Deadpool",
    "genero":"Ação",
    "duracao":127,
    "classificacao":18
}

###
PUT http://localhost:3000/editar-filme/2
Content-Type: application/json

{
    "titulo":"Avatar 2",
    "genero":"Ficção",
    "duracao":192,
    "classificacao":12
}

###
DELETE http://localhost:3000/deletar-filme/2
